apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::390136424408:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
       - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::390136424408:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-R3U4DIN1PK0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: 2020-03-02T12:46:08Z
  name: aws-auth
  namespace: kube-system
  resourceVersion: "907"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c99ec883-5c83-11ea-8042-0ab3f2192e7c


apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<ACCOUNT-ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<ACCOUNT-ID>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KK354O3ELCAL
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap


